-- ============================================================
-- ucheck1 — Clean schema migration
-- Run this in Supabase SQL Editor (new project)
-- ============================================================

-- ─── users ───────────────────────────────────────────────────
create table public.users (
  id            uuid primary key references auth.users(id) on delete cascade,
  created_at    timestamptz default now(),
  name          text,
  last_name     text,
  id_number     text,
  user_role     text,
  email         text,
  user_categorie text,
  profile_url   text
);

alter table public.users enable row level security;

create policy "Users can read own row"
  on public.users for select
  using (auth.uid() = id);

create policy "Users can insert own row"
  on public.users for insert
  with check (auth.uid() = id);

create policy "Users can update own row"
  on public.users for update
  using (auth.uid() = id);


-- ─── announcement ────────────────────────────────────────────
create table public.announcement (
  id         bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  uuid       uuid references auth.users(id) on delete set null,
  last_name  text,
  name       text,
  content    text
);

alter table public.announcement enable row level security;

create policy "All authenticated users can read announcements"
  on public.announcement for select
  using (auth.role() = 'authenticated');

create policy "Authenticated users can insert announcements"
  on public.announcement for insert
  with check (auth.role() = 'authenticated');

create policy "Authenticated users can update announcements"
  on public.announcement for update
  using (auth.role() = 'authenticated');

create policy "Authenticated users can delete announcements"
  on public.announcement for delete
  using (auth.role() = 'authenticated');


-- ─── calendarAppointments ────────────────────────────────────
create table public."calendarAppointments" (
  id                bigint generated by default as identity primary key,
  created_at        timestamptz default now(),
  start_at          text,
  end_at            text,
  subject           text,
  color             text,
  date              text,
  faculty           text,
  department        text,
  principal_teacher text,
  exam_level        text
);

alter table public."calendarAppointments" enable row level security;

create policy "All authenticated users can read calendar"
  on public."calendarAppointments" for select
  using (auth.role() = 'authenticated');

create policy "Authenticated users can insert calendar"
  on public."calendarAppointments" for insert
  with check (auth.role() = 'authenticated');

create policy "Authenticated users can update calendar"
  on public."calendarAppointments" for update
  using (auth.role() = 'authenticated');

create policy "Authenticated users can delete calendar"
  on public."calendarAppointments" for delete
  using (auth.role() = 'authenticated');


-- ─── student_lists ───────────────────────────────────────────
create table public.student_lists (
  id         bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name       text,
  last_name  text,
  id_number  text,
  uuid       uuid references auth.users(id) on delete set null,
  avatar_url text
);

alter table public.student_lists enable row level security;

create policy "All authenticated users can read student list"
  on public.student_lists for select
  using (auth.role() = 'authenticated');

create policy "Authenticated users can insert into student list"
  on public.student_lists for insert
  with check (auth.role() = 'authenticated');

create policy "Authenticated users can delete from student list"
  on public.student_lists for delete
  using (auth.role() = 'authenticated');
